### ISSUE TITLE
该程序不能在windows下运行，建议添加一个.bat脚本支持windows运行。

### ISSUE THREAD

**Issue by leihenshang** [wizarot/redis-cli#1]
这个是yii2的，你可以参考一下。文档里也建议说明目前支持的操作系统，然后似乎没有找到文档中说的v1.0.0分支？
`@echo off

rem -------------------------------------------------------------
rem  Yii command line bootstrap script for Windows.
rem -------------------------------------------------------------

@setlocal

set YII_PATH=%~dp0

if "%PHP_COMMAND%" == "" set PHP_COMMAND=php.exe

"%PHP_COMMAND%" "%YII_PATH%yii" %*

@endlocal
`

**Comment by wizarot** [comment]
说的对! 应该加一个支持windows.  我这边手上没windows系统,稍等抽空处理下.
你暂时可以用 > php.exe  redis-cli 来试试直接执行.

是没v1.0.0 ,打标签时候手抖~ 实际是 v1.0

**Comment by wizarot** [comment]
做了一个bat. 但未必能用? 谁给帮忙测试下?

**Comment by leihenshang** [comment]
测试在windows下可以使用。就是使用发现显示其实不够清晰。
比如类型显示的时候蓝色底色，不如直接白色的底色好用。
可以把STATUS 的下划线干掉。感觉有点花哨，愚见。见谅。

**Comment by wizarot** [comment]
显示颜色的问题确实需要解决.  
这个和客户端颜色主题,还有bash颜色主题都有关系,互相作用.
没有办法做到完美搭配,所以将在下一个版本增加自定义颜色功能,所有颜色都将放在配置文件中,可以自行定义.  这样发现颜色影响显示清晰的,可以自行调整.
